#!/bin/bash

basedir=`dirname $0`

if type -p ipython; then
    _ipython=ipython
else
    echo "no ipython executable found in PATH"
fi

if [[ "$_ipython" ]]; then
    version=$("$_ipython" --version 2>/dev/null)
    if [[ $version =~ ^0 ]]; then
        echo "ipython version below 1.0 is not supported"
    else
        ipython --gui=gtk -i $basedir/source/qtlab_shell.py -- "$@"
    fi
fi
